
spring:
  application:
    name: loan-payment-service
  server:

  datasource:
    url: jdbc:h2:mem:loanpaymentdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
    default-schema: PUBLIC
    drop-first: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.bancx.loanpayment: DEBUG
    org.springframework.web: INFO
    liquibase: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
