package com.bancx.loanpayment.payment.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing a payment made towards a loan.
 * Contains payment details including amount, associated loan ID, and timestamp.
 *
 * Uses Lombok annotations for boilerplate code generation.
 *
 * @author Khanyisani Luyanda Ntabeni
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Payment {

    /**
     * Primary key for Payment entity, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId;

    /**
     * Identifier of the loan this payment is applied to.
     */
    private Long loanId;

    /**
     * Amount of the payment made.
     */
    private BigDecimal paymentAmount;

    /**
     * Timestamp of when the payment was created.
     * Defaults to the current date and time when built via Lombok builder.
     */
    @Builder.Default
    private LocalDateTime timestamp = LocalDateTime.now();
}
